"""added impact to change

Revision ID: 458d61efe993
Revises: 95cbcbb35486
Create Date: 2022-08-01 23:32:22.641930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458d61efe993'
down_revision = '95cbcbb35486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('impact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'impact')
    # ### end Alembic commands ###
