"""add dates

Revision ID: 8ccf2d653e65
Revises: bfade3c1ecc8
Create Date: 2022-07-02 13:48:20.820901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccf2d653e65'
down_revision = 'bfade3c1ecc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('change_comment', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('configuration_data', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('incident', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('incident_comment', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('incident_configuration', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('known_errors', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('problem', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('problem_comment', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_comment', 'created_on')
    op.drop_column('problem', 'created_on')
    op.drop_column('known_errors', 'created_on')
    op.drop_column('incident_configuration', 'created_on')
    op.drop_column('incident_comment', 'created_on')
    op.drop_column('incident', 'created_on')
    op.drop_column('configuration_data', 'created_on')
    op.drop_column('change_comment', 'created_on')
    op.drop_column('change', 'created_on')
    # ### end Alembic commands ###
