"""change taken by

Revision ID: 95cbcbb35486
Revises: 8ccf2d653e65
Create Date: 2022-07-04 11:56:28.322166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cbcbb35486'
down_revision = '8ccf2d653e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('taken_by_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'taken_by_id')
    # ### end Alembic commands ###
