"""add change comment

Revision ID: bfade3c1ecc8
Revises: d002349f4782
Create Date: 2022-07-02 13:42:58.218664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfade3c1ecc8'
down_revision = 'd002349f4782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incident_comment', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('problem_comment', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_comment', 'user_id')
    op.drop_column('incident_comment', 'user_id')
    op.drop_table('change_comment')
    # ### end Alembic commands ###
