# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x']

    steps:
    - uses: actions/checkout@v3
    - name: Use Python3
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
    - run: pip install -r requirements.txt
    - run: python -m pytest
